const ActIntroSec = () => {
    return (

        <div class="actintro">
              <h1 className="actinth">A thought for</h1>
              <img className= "actintsh"src="sh.png" alt="a better tomorrow"> </img>
              <p class="actintpara">A beautiful thought can change the world. The last time you told someone it's going to be okay? Yes. That.
                This community is formed by a group of young individuals, who care about the future of this society. </p>
                <p className="actintpara">Coming from privileged 
                backgrounds, we understand that there are various problems we never face but we know society as a whole is privy to. We believe 
                that a human is not made by the things he does for himself but by the things he is willing to do for others.  With all the love 
                and care that we have, we want to bring a change in the lives of people, in any and every way possible.</p>

          </div>

      );
}
 
export default ActIntroSec;